config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|pt|es/ do

    scope ':tour' do
        get 'around/arte'

        get 'around/castelos'

        get 'around/centro'

        get 'around/palacio'

        get 'around/peregrinacao'

        get 'around/templarios'

        get 'around/romano'

        get 'around/ria'

        get 'around/amor'

        get 'around/xisto'

        get 'coimbra/unesco'

        get 'coimbra/fado'

        get 'coimbra/gastronomy'

        get 'coimbra/jewish'

        get 'coimbra/moonlight'

        get 'coimbra/riverside'

        get 'coimbra/peddypaper'
    end

    get 'general/partners'

    get 'general/team'

    get 'general/faq'

    get 'tour/coimbra'

    get 'tour/around'

    get 'tour/tailored'

    get 'index/cover'

    root 'index#cover'

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  private
  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
  end

	def extract_locale
	  parsed_locale = params[:locale]
	  I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
	end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/around_controller.rb
class AroundController < ApplicationController
  def arte
  end

  def castelos
  end

  def centro
  end

  def palacio
  end

  def peregrinacao
  end

  def templarios
  end

  def xisto
  end

  def romano
  end

  def ria
  end

  def amor
  end
end

app/controllers/coimbra_controller.rb
class CoimbraController < ApplicationController
  def unesco
  end

  def fado
  end

  def gastronomy
  end

  def jewish
  end

  def moonlight
  end

  def riverside
  end

  def peddypaper
  end
end

app/controllers/general_controller.rb
class GeneralController < ApplicationController
  def partners
  end

  def team
  end

  def faq
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def cover
  end
end

app/controllers/tour_controller.rb
class TourController < ApplicationController
  def coimbra
  end

  def around
  end

  def tailored
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/around_helper.rb
module AroundHelper
end

app/helpers/coimbra_helper.rb
module CoimbraHelper
end

app/helpers/general_helper.rb
module GeneralHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/tour_helper.rb
module TourHelper
end

app/views/around/amor.html.erb
<%= render file: "layouts/list_tour", 

locals: {
	id: {
	    cover: "amor-cover", info: "amor-info", details: "amor-details"
    },
    cover_en: {
        title: "Tales Of Love: Pedro And Inês",
        subtitle: "Fullday Tour Of Coimbra And Alcobaça"
        },
    cover_pt: {
        title: "Lendas De Amor: Pedro & Inês",
        subtitle: "Visita De Dia Completo A Coimbra E Alcobaça"
    },
    meeting_point: {
        name: "Combinar",
    },
    data_pt: {
        reservation: "Disponível de 3ªf a Domingo, excepto 1 de Janeiro, Domingo de Páscoa, 1 de Maio, 20 de Agosto e 25 de Dezembro,  mediante consulta de disponibilidade de guia",
        cost: "80€/pessoa, min 2 pessoas ou valor equivalente"
    },
    data_en: {
        reservation: "Available from Tuesday to Sunday, except 1st January, Easter Sunday, 1st of May, 20th August and 25th December, under request of guide’s availability | From 9am to 6pm",
        cost: "80€/person . Min 2 people or equivalent price"
    },
    text_pt: {
        intro: "Nesta visita guiada vamos conhecer todos os detalhes da trágica – e mais bela - história de amor de Portugal, à medida que percorremos alguns dos locais onde tudo se passou no século XIV!",
        more: [
            "Iniciaremos o dia com uma caminhada pelos espaços citadinos ligados a esta temática, conhecendo os Parques Verdes do Rio Mondego que desde 2006 é atravessado por uma belíssima Ponte Pedonal e Ciclável conhecida como “Pedro & Inês”. Conheceremos ainda o Mosteiro de Santa Clara-a-Velha e em seguida iremos de visita aos Jardins da Quinta das Lágrimas, nome dado a este espaço verde onde se respira tranquilidade devido às desventuras do romance entre a Dama Inês de Castro e o príncipe D. Pedro I de Portugal. Aqui encontraremos vestígios da história de amor destas duas personagens da História de Portugal, por entre árvores centenárias, ruínas medievais e neo-góticas, diversos tanques e regatos!",
            "Após pausa para almoço, partiremos para Alcobaça onde visitaremos a Abadia deste Mosteiro Património Mundial da Humanidade e simultaneamente Panteão Nacional, eterna morada de Pedro e Inês. Após a morte trágica de Inês de Castro, D. Pedro ordena a construção de duas grandes arcas tumulares em estilo gótico para deposição dos seus restos mortais. Estes túmulos jazem hoje em dia no transepto da Abadia de Alcobaça, frente a frente para sempre.",
            "Antes de regressarmos a Coimbra vamos visitar uma das pastelarias locais para experimentar alguns dos caprichos gastronómicos regionais. Aqui poderá experimentar doces conventuais premiados tais como as famosas Cornucópias, Castanhas de ovo, Delícia de amêndoas, Diário de Inês, Ovos do Paraíso, Pudim de São Bernardo, Torrão de Abadessa, Torresmo do Céu… entre outras delícias que o vão deixar apaixonado por este sítio!"]
    },
    text_en: {
        intro: "In this guided tour we will unveil all the details of the most tragic – as well as the most beautiful – love story in the History of Portugal, as we travel along some of the sites where it all took place during the 14th Century!",
        more: [
            "Our day starts with a foot walk through the city sites that are directly connected with this tragic tale. First the Mondego Green Parks which are connected by the  lovely pedestrian bridge known as “Pedro & Inês” since 2006. Next we will visit the Monastery of Santa Clara-a-Velha and the Quinta das Lágrimas Gardens, a name that was given as a reminder of the love filled adventures of Lady Inês de Castro and Prince D. Pedro I from Portugal.",
            "After a short lunch break, we will be driving to Alcobaça where we can visit the Abbey as part of the World Heritage Monastery as well as the National Pantheon, the eternal resting place of Pedro and Inês. After the tragic death of Inês de Castro, D. Pedro ordered the construction of two big gothic styled tombs. Both of these still remain at the transept of the Alcobaça Abbey, fronting each other forever.",
            "Before returning to Coimbra there will be a quick stop at one of the local pastries to taste some of the regional gastronomic treats. Here you will be able to experience prized conventual pastry like the famous Cornucópias, Castanhas de ovo, Delícia de amêndoas, Diário de Inês, Ovos do Paraíso, Pudim de São Bernardo, Torrão de Abadessa, Torresmo do Céu… by the end of it you will be deeply in love with this place!"
        ],
    },
    poi: {
        list_pt: [
            "Rio Mondego", 
            "Ponte Pedro & Inês", 
            "Mosteiro de Santa Clara-a-Velha e Canto dos Amores", 
            "Jardins da Quinta das Lágrimas com o seu Retiro Medieval", 
            "Retiro Romântico", 
            "Fonte dos Amores", 
            "Fonte das Lágrimas", 
            "Auditório Camões", 
            "Sequoias de Wellington", 
            "Centro Histórico de Alcobaça", 
            "Abadia do Mosteiro de Alcobaça com Túmulos de Pedro e Inês", 
            "Pinhal de Leiria."
        ],
        list_en: [
            "Mondego River", 
            "Pedro & Inês Pedestrian Bridge", 
            "Monastery of Santa Clara-a-Velha and Corner of Love", 
            "Gardens of Quinta das Lágrimas and its Medieval Retreat", 
            "Romantic Garden", 
            "Fountain of Love", 
            "Fountain of Tears", 
            "Camões Auditorium", 
            "Wellington Sequoia", 
            "Historical Center of Alcobaça", 
            "Abbey of the Monastery of Alcobaça and the Tombs of Pedro & Inês", 
            "Leiria Pinewood."
        ]
    },
    poi2: {},
    optional: {
        lead_pt:"Se pretender uma visita privada, contacte-nos! Teremos o maior gosto em adaptar o roteiro de acordo com as suas preferências pessoais e curiosidades, e dar-lhe assim a conhecer o melhor de Portugal permitindo-lhe usufruir plenamente do território e da sua cultura… ao seu ritmo… no seu idioma... e na companhia de um guia local!",
        lead_en: "Ask for a tailored tour: we will gladly adapt the route according  to your personal preferences, allowing you to discover everything you would want to know about the portuguese culture… accompanied by a local guide!",
        optional_pt: [
        ],
        optional_en: [
        ]
    },
    fotos: [
        "/images/around/amor/foto3.jpg",
        "/images/around/amor/foto2.jpg",
        "/images/around/amor/foto1.jpg",
        "/images/around/amor/foto4.jpg",
        "/images/around/amor/foto5.jpg",
        "/images/around/amor/foto6.jpg",
    ],
    icon: [
        2,7
    ],
} %>

app/views/index/cover.html.erb
<!--COVER-->
<header id="cover" class="cover-background">
	<div class="container-fluid">
		<div class="row">
			<div class="header-text">
				<h1 id="homeHeading">
					<%= t('index.hello') %>
				</h1>
                <hr class="orange">
				<h3><%= t('index.intro') %></h3>
			</div>
		</div>
        <div class="row arrow">
            <a class="page-scroll" href="#about" data-turbolinks="false">
                <h3><i class="fa fa-angle-down fa-5x"></i></h3>
            </a>
        </div>
	</div>
</header>

<section id="about">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 text-center">
				<img src="\images\logo\gowalks_logo_mini.png" class="img-responsive center-block" alt="GOwalks logo" width="50%">
                <hr class="orange">
				<h3><%= t('index.gowalks') %></h3>

                <div id="about-links">

                    <div class="row">
                        <div class="col-xs-4">
                            <%= link_to url_for(general_team_path(locale: I18n.locale)), class: "btn-link" do %>
                                <p><i class="fa fa-users fa-3x orange-color" aria-hidden="true"></i></p>
                                <p><%= t('general.team') %></p>
                            <% end %>
                        </div>
                        <div class="col-xs-4">
                            <%= link_to url_for(general_partners_path(locale: I18n.locale)), class: "btn-link" do %>
                                <p><i class="fa fa-link fa-3x orange-color" aria-hidden="true"></i></p>
                                <p><%= t('general.partners') %></p>
                            <% end %>
                        </div>
                        <div class="col-xs-4">
                            <%= link_to url_for(general_faq_path(locale: I18n.locale)), class: "btn-link" do %>
                                <p><i class="fa fa-question-circle fa-3x orange-color" aria-hidden="true"></i></p>
                                <p><%= t('general.faq') %></p>
                             <% end %>
                        </div>
                    </div>
                </div>

                <a class="page-scroll" href="#coimbra-tour" data-turbolinks="false">
                    <h3><i class="fa fa-angle-down fa-5x"></i></h3>
                </a></li>
			</div>
		</div>
	</div>
</section>

<section id="coimbra-tour" class="cover-background">
    <div class="container-fluid cover-tour transparent-layer">
        <div class="row cover-text">
            <div>
                <h2><%= t('tours.t1') %></h2>
                <hr class="orange">
                <h3><%= t('index.coimbra') %></h3>
                <%= link_to t('index.button'), url_for(tour_coimbra_path(locale: I18n.locale)), class: "btn btn-lg btn-customize"%>
            </div>
        </div>
        <div class="row arrow">
            <a class="page-scroll" href="#around-coimbra-tour" data-turbolinks="false">
                <h3><i class="fa fa-angle-down fa-5x"></i></h3>
            </a></li>
        </div>
    </div>
</section>
<section id="around-coimbra-tour" class="cover-background">
    <div class="container-fluid cover-tour transparent-layer">
        <div class="row cover-text">
            <div>
                <h2><%= t('tours.t2') %></h2>
                <hr class="orange">
                <h3><%= t('index.around') %></h3>
                <%= link_to t('index.button'), url_for(tour_around_path(locale: I18n.locale)), class: "btn btn-lg btn-customize"%>
            </div>
        </div>
        <div class="row arrow">
            <a class="page-scroll" href="#tailored-tour" data-turbolinks="false">
                <h3><i class="fa fa-angle-down fa-5x"></i></h3>
            </a></li>
        </div>
    </div>
</section>
<section id="tailored-tour" class="cover-background">
    <div class="container-fluid cover-tour transparent-layer">
        <div class="row cover-text ">
            <div>
                <h2><%= t('tours.t3') %></h2>
                <hr class="orange">
                <h3><%= t('index.tailored') %></h3>
                <%= link_to t('index.button'), url_for(tour_tailored_path(locale: I18n.locale)), class: "btn btn-lg btn-customize"%>
            </div>
        </div>
        <div class="row arrow">
            <a class="page-scroll" href="#reservations" data-turbolinks="false">
                <h3><i class="fa fa-angle-down fa-5x"></i></h3>
            </a></li>
        </div>
    </div>
</section>

app/views/layouts/around.html.erb
<%= render file: "layouts/application" %>

app/views/layouts/coimbra.html.erb
<%= render file: "layouts/application" %>

app/views/tour/around.html.erb
<!--COVER-->
<header id="around_cover" class="cover-background">
	<div class="container-fluid transparent-layer">
		<div class="row">
			<div class="header-text">
				<h1><%= t('tours.t2') %></h1>
                <hr class="orange">
				<h5><%= t('around.subtitle') %></h5>
			</div>
		</div>
        <div class="row arrow">
            <a class="page-scroll" href="#around_page_information" data-turbolinks="false">
                <h3><i class="fa fa-angle-down fa-5x"></i></h3>
            </a></li>
        </div>
	</div>
</header>

<section id="around_page_information">
	<div class="container-fluid">
		<div class="row container-text-align">
			<div class="col-lg-8 col-lg-offset-2">			
				<h2><%= t('around.title') %></h2>
                <hr class="dark">
                <h4><%= t('around.intro') %></h4>
			</div>
		</div>

        <div class="row">
            
            <div class="tour-item-wrapper col-sm-6 col-md-4">
                <div class="tour-item">
                    <%= link_to url_for(around_arte_path(:tour, locale: I18n.locale)) do %>
                        <div class="photo-item">
                            <img src="/images/around/sq/arte.jpg" class="tour-image">
                            <div class='description'>  
                                <h3 class='description_content'><h3><%= t('around.t1') %></h3>  
                            </div> 
                            <div class="overlay-info">
                                <i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class="tour-item-wrapper col-sm-6 col-md-4">
                <div class="tour-item">
                    <%= link_to url_for(around_castelos_path(:tour, locale: I18n.locale)) do %>
                        <div class="photo-item">
                            <img src="/images/around/sq/castelos.jpg" class="tour-image">
                            <div class='description'>  
                                <h3 class='description_content'><%= t('around.t2') %></h3>  
                            </div> 
                            <div class="overlay-info">
                                <i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class="tour-item-wrapper col-sm-6 col-md-4">
                <div class="tour-item">
                    <%= link_to url_for(around_centro_path(:tour, locale: I18n.locale)) do %>
                        <div class="photo-item">
                            <img src="/images/around/sq/centro2.jpg" class="tour-image">
                            <div class='description'>  
                                <h3 class='description_content'><%= t('around.t3') %></h3>  
                            </div> 
                            <div class="overlay-info">
                                <i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
            
            <div class="tour-item-wrapper col-sm-6 col-md-4">
                <div class="tour-item">
                    <%= link_to url_for(around_palacio_path(:tour, locale: I18n.locale)) do %>
                        <div class="photo-item">
                            <img src="/images/around/sq/palacio.jpg" class="tour-image">
                            <div class='description'>  
                                <h3 class='description_content'><%= t('around.t4') %></h3>  
                            </div> 
                            <div class="overlay-info">
                                <i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class="tour-item-wrapper col-sm-6 col-md-4">
                <div class="tour-item">
                    <%= link_to url_for(around_peregrinacao_path(:tour, locale: I18n.locale)) do %>
                        <div class="photo-item">
                            <img src="/images/around/sq/peregrinacao.jpg" class="tour-image">
                            <div class='description'>  
                                <h3 class='description_content'><%= t('around.t5') %></h3>  
                            </div> 
                            <div class="overlay-info">
                                <i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class="tour-item-wrapper col-sm-6 col-md-4">
                <div class="tour-item">
                    <%= link_to url_for(around_templarios_path(:tour, locale: I18n.locale)) do %>
                        <div class="photo-item">
                            <img src="/images/around/sq/temp2.jpg" class="tour-image">
                            <div class='description'>  
                                <h3 class='description_content'><%= t('around.t6') %></h3>  
                            </div> 
                            <div class="overlay-info">
                                <i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class="tour-item-wrapper col-sm-6 col-md-4">
                <div class="tour-item">
                    <%= link_to url_for(around_xisto_path(:tour, locale: I18n.locale)) do %>
                        <div class="photo-item">
                            <img src="/images/around/sq/aldeiaxisto.jpg" class="tour-image">
                            <div class='description'>  
                                <h3 class='description_content'><%= t('around.t7') %></h3>  
                            </div> 
                            <div class="overlay-info">
                                <i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class="tour-item-wrapper col-sm-6 col-md-4">
                <div class="tour-item">
                    <%= link_to url_for(around_romano_path(:tour, locale: I18n.locale)) do %>
                        <div class="photo-item">
                            <img src="/images/around/sq/romano.jpg" class="tour-image">
                            <div class='description'>  
                                <h3 class='description_content'><%= t('around.t8') %></h3>  
                            </div> 
                            <div class="overlay-info">
                                <i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class="tour-item-wrapper col-sm-6 col-md-4">
                <div class="tour-item">
                    <%= link_to url_for(around_amor_path(:tour, locale: I18n.locale)) do %>
                        <div class="photo-item">
                            <img src="/images/around/sq/amor.jpg" class="tour-image">
                            <div class='description'>  
                                <h3 class='description_content'><%= t('around.t9') %></h3>  
                            </div> 
                            <div class="overlay-info">
                                <i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class="tour-item-wrapper col-sm-6 col-md-4">
                <div class="tour-item">
                    <%= link_to url_for(around_ria_path(:tour, locale: I18n.locale)) do %>
                        <div class="photo-item">
                            <img src="/images/around/sq/ria2.jpg" class="tour-image">
                            <div class='description'>  
                                <h3 class='description_content'><%= t('around.t10') %></h3>  
                            </div> 
                            <div class="overlay-info">
                                <i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

        </div>
        
    </div>
</section>

app/views/tour/coimbra.html.erb
<!--COVER-->
<header id="coimbra_cover" class="cover-background">
	<div class="container-fluid transparent-layer">
		<div class="row">
			<div class="header-text">
				<h1><%= t('tours.t1') %></h1>
                <hr class="orange">
				<h5><%= t('index.coimbra') %></h5>
			</div>
		</div>
        <div class="row arrow">
            <a class="page-scroll" href="#coimbra_page_information" data-turbolinks="false">
                <h3><i class="fa fa-angle-down fa-5x"></i></h3>
            </a></li>
        </div>
	</div>
</header>

<section id="coimbra_page_information">
	<div class="container-fluid">
		
        <div class="row container-text-align">
			<div class="col-lg-8 col-lg-offset-2">			
				<h2><%= t('coimbra.title') %></h2>
                <hr class="dark">
                <h4><%= t('coimbra.intro') %></h4>
			</div>
		</div>

        <div class="row">
            
            <div class="tour-item-wrapper col-sm-6 col-md-4">
                <div class="tour-item">
                    <%= link_to url_for(coimbra_unesco_path(:tour, locale: I18n.locale)) do %>
                        <div class="photo-item">
                            <img src="/images/coimbra/unesco.jpg" class="tour-image">
                            <div class='description'>  
                                <h3 class='description_content'><%= t('coimbra.t1') %></h3>  
                            </div> 
                            <div class="overlay-info">
                                <i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class="tour-item-wrapper col-sm-6 col-md-4">
                <div class="tour-item">
                    <%= link_to url_for(coimbra_fado_path(:tour, locale: I18n.locale)) do %>
                        <div class="photo-item">
                            <img src="/images/coimbra/fado.jpg" class="tour-image">
                            <div class='description'>  
                                <h3 class='description_content'><%= t('coimbra.t2') %></h3>  
                            </div> 
                            <div class="overlay-info">
                                <i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class="tour-item-wrapper col-sm-6 col-md-4">
                <div class="tour-item">
                    <%= link_to url_for(coimbra_gastronomy_path(:tour, locale: I18n.locale)) do %>
                        <div class="photo-item">
                            <img src="/images/coimbra/gastronomic.jpg" class="tour-image">
                            <div class='description'>  
                                <h3 class='description_content'><%= t('coimbra.t3') %></h3>  
                            </div> 
                            <div class="overlay-info">
                                <i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
            
            <div class="tour-item-wrapper col-sm-6 col-md-4">
                <div class="tour-item">
                    <%= link_to url_for(coimbra_jewish_path(:tour, locale: I18n.locale)) do %>
                        <div class="photo-item">
                            <img src="/images/coimbra/jewish2.jpg" class="tour-image">
                            <div class='description'>  
                                <h3 class='description_content'><%= t('coimbra.t4') %></h3>  
                            </div> 
                            <div class="overlay-info">
                                <i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class="tour-item-wrapper col-sm-6 col-md-4">
                <div class="tour-item">
                    <%= link_to url_for(coimbra_moonlight_path(:tour, locale: I18n.locale)) do %>
                        <div class="photo-item">
                            <img src="/images/coimbra/moonlight.jpg" class="tour-image">
                            <div class='description'>  
                                <h3 class='description_content'><%= t('coimbra.t5') %></h3>  
                            </div> 
                            <div class="overlay-info">
                                <i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class="tour-item-wrapper col-sm-6 col-md-4">
                <div class="tour-item">
                    <%= link_to url_for(coimbra_riverside_path(:tour, locale: I18n.locale)) do %>
                        <div class="photo-item">
                            <img src="/images/coimbra/riverside2.jpg" class="tour-image">
                            <div class='description'>  
                                <h3 class='description_content'><%= t('coimbra.t6') %></h3>  
                            </div> 
                            <div class="overlay-info">
                                <i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

            <div class="tour-item-wrapper col-sm-6 col-md-4">
                <div class="tour-item">
                    <%= link_to url_for(coimbra_peddypaper_path(:tour, locale: I18n.locale)) do %>
                        <div class="photo-item">
                            <img src="/images/coimbra/peddypaper2.jpg" class="tour-image">
                            <div class='description'>  
                                <h3 class='description_content'><%= t('coimbra.t7') %></h3>  
                            </div> 
                            <div class="overlay-info">
                                <i class="fa fa-plus-circle fa-3x" aria-hidden="true"></i>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>

        </div>
        
    </div>
</section>